require("dotenv").config();
const PinataSDK = require("@pinata/sdk");

const pinata = new PinataSDK(
  process.env.PINATA_API_KEY,
  process.env.PINATA_API_SECRET
);

async function uploadToIPFS(code, patternName, description, codeHash) {
  try {
    // Upload the HTML page directly as a file
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${patternName} — Living Protocol Builder</title>
<style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { background:#0a0a24; color:#e2e8f0; font-family:'JetBrains Mono',monospace; padding:40px; min-height:100vh; }
  .card { background:rgba(14,16,40,0.8); border:1px solid rgba(100,130,225,0.3); border-radius:16px; padding:30px; max-width:900px; margin:0 auto; }
  h1 { color:#60a5fa; font-size:1.5rem; margin-bottom:8px; }
  .badge { display:inline-block; background:rgba(59,130,246,0.2); color:#60a5fa; padding:4px 12px; border-radius:20px; font-size:0.7rem; margin-right:8px; }
  .hash { color:#f59e0b; font-size:0.65rem; margin:12px 0; word-break:break-all; }
  .code { background:#000; border:1px solid rgba(100,130,225,0.2); border-radius:12px; padding:24px; margin-top:20px; overflow-x:auto; font-size:0.75rem; line-height:1.6; color:#8ab4f8; white-space:pre-wrap; }
  .footer { margin-top:24px; color:#64748b; font-size:0.7rem; text-align:center; }
  .footer a { color:#60a5fa; }
</style>
</head>
<body>
<div class="card">
  <h1>${patternName}</h1>
  <p style="color:#94a3b8;margin:8px 0 16px;">${description || 'AI-Generated Smart Contract'}</p>
  <span class="badge">Venice AI</span>
  <span class="badge">Living Protocol Builder</span>
  <span class="badge">IPFS Verified</span>
  <div class="hash">🔐 SHA256: ${codeHash || 'N/A'}</div>
  <div class="code">${code.replace(/</g,'&lt;').replace(/>/g,'&gt;')}</div>
  <div class="footer">
    Generated by <a href="https://living-protocol.vercel.app">Living Protocol Builder</a> — Powered by Venice AI<br>
    Stored permanently on IPFS · ${new Date().toISOString()}
  </div>
</div>
</body>
</html>`;

    const result = await pinata.pinJSONToIPFS({
      name: patternName,
      description: description,
      code: code,
      codeHash: codeHash,
      html: html,
      type: "contract",
      generator: "Living Protocol Builder — Venice AI",
      network: "Base Sepolia",
      timestamp: new Date().toISOString(),
    });
    
    console.log(`   📦 IPFS CID: ${result.IpfsHash}`);
    return {
      cid: result.IpfsHash,
      url: `https://gateway.pinata.cloud/ipfs/${result.IpfsHash}`,
      // Direct HTML view
      htmlUrl: `https://gateway.pinata.cloud/ipfs/${result.IpfsHash}?format=html`,
    };
  } catch(e) {
    console.log(`   ⚠️ IPFS upload skipped: ${e.message.slice(0,60)}`);
    return null;
  }
}

module.exports = { uploadToIPFS };
